Add example on how to bind a material to a mesh
NVIDIA-Omniverse/OpenUSD-Code-Samples pull request #55
Opened 2024-06-10 17:33 UTC by cadop

The technical term is bind, but we put in the description 'attach' because I suspect most people will search for and understand that phrase easier.

2024-06-11 15:02 UTC, mati-nvidia requested changes

2024-06-11 15:02 UTC, mati-nvidia commented on source/materials/attach-mdl-material/py_usd.py
> +shader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(1.0)
This could be improved by following our style here: https://github.com/NVIDIA-Omniverse/OpenUSD-Code-Samples/blob/ac52ad832bbe130d0cdbf0405f0486f6cfce413f/source/prims/check-prim-exists/py_usd.py#L7

1. Create a function that accepts a UsdShade.Material and Usd.Prim to attach it to. It basically just runs the bind function on L32 here.
2. Move the mesh and material creation to Full Usage section.
3. `header.md` can mention that this example is focused on binding and it is applicable to any type of UsdShade.Material. You can link out to the UsdPreviewSurface and MDL samples for different examples of creating materials.

2024-06-11 15:02 UTC, mati-nvidia commented on source/materials/attach-mdl-material/py_usd.py
> +stage = omni.usd.get_context().get_stage()
Because this is a vanilla USD example, let's create a stage in memory instead of using `omni.usd`: https://github.com/NVIDIA-Omniverse/OpenUSD-Code-Samples/blob/ac52ad832bbe130d0cdbf0405f0486f6cfce413f/source/prims/check-prim-exists/py_usd.py#L18

2024-06-11 17:05 UTC, cadop commented on source/materials/attach-mdl-material/config.toml
> +title = "Attach a UsdPreviewSurface Material to Mesh"
I think assign makes sense, i'll try to work in 'attach' and 'bind in the header instead.

2024-06-11 18:59 UTC, cadop commented on source/materials/attach-mdl-material/py_usd.py
> +shader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(1.0)
Is there a convention for hyperlinking to other examples within this repo? To avoid broken links on the next update?

2024-06-11 19:01 UTC, mati-nvidia commented on source/materials/attach-mdl-material/py_usd.py
> +shader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(1.0)
In this cheatsheet, the last example shows how to create a link using a relative path from your current sample: https://github.com/NVIDIA-Omniverse/OpenUSD-Code-Samples/blob/main/CODE-SAMPLE-GUIDELINES.md#markdown-cheatsheet

2024-06-11 20:41 UTC, cadop commented on source/materials/attach-mdl-material/py_usd.py
> +shader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(1.0)
updated header to include links to other materials

2024-06-11 20:48 UTC, cadop commented on source/materials/attach-mdl-material/py_usd.py
> +shader.CreateInput("ior", Sdf.ValueTypeNames.Float).Set(1.0)
created a function to wrap bind

2024-06-11 23:11 UTC, mati-nvidia requested changes

2024-06-11 23:11 UTC, mati-nvidia commented on source/materials/attach-mdl-material/py_usd.py
> +def bind_material(prim, mtl):
Sorry. I missed this earlier. You also need to apply the API schema for usdchecker to not throw errors:
`bindingAPI = UsdShade.MaterialBindingAPI.Apply(target_prim)`

2024-06-11 23:11 UTC, mati-nvidia commented on source/materials/attach-mdl-material/config.toml
> +title = "Assign a UsdPreviewSurface Material to Mesh"
I think we can just make this generic: `Assign a Material to a Mesh`. The sample folder should match: `assign-material`. Thanks @cadop! Sorry to nitpick.

2024-06-12 18:47 UTC, cadop reviewed
> I think we can just make this generic: `Assign a Material to a Mesh`. The sample folder should match: `assign-material`. Thanks @cadop! Sorry to nitpick. 

You want to make a new folder instead of the existing materials snippets, or did i misread this?

2024-06-25 15:31 UTC, mati-nvidia approved these changes

2024-06-25 15:31 UTC, merged